"""
Compound taxonomy and SMILES catalog for the Chemistry Recognizer project.

This module is STANDALONE: it has no imports from `src/` and can be safely
imported by both `data/generate_dataset.py` and notebooks/scripts.

Public API:
    COMPOUNDS : list[dict]                       — flat list of every compound
    TAXONOMY  : dict                              — nested structure for UI navigation
    get_compounds(category, subcategories, difficulty) -> list[dict]

Every compound dict has the same set of keys; see the comment block below
for the schema.
"""

from typing import Iterable, Optional, List, Dict

# ---------------------------------------------------------------------------
# Schema (per compound):
#   id                    str  — unique slug, lowercase, filesystem-safe
#   name_es               str  — Spanish name (ASCII, no accents)
#   name_display          str  — Spanish display name (with accents)
#   name_iupac            str  — IUPAC / nomenclatura sistemática
#   formula               str  — ASCII formula
#   formula_display       str  — formula with Unicode subscripts
#   smiles                str  — valid RDKit SMILES
#   category              str  — "inorganica" | "organica"
#   subcategory           str  — filesystem-safe slug, key in TAXONOMY
#   subcategory_display   str  — Spanish display name with accents
#   difficulty            str  — "basico" | "intermedio" | "avanzado"
#   nomenclature_note     str  — brief educational note (Spanish)
#   ionic                 bool — True forces formula-text rendering
# ---------------------------------------------------------------------------


def _C(**kw) -> Dict:
    """Helper to build a compound dict with all required keys present."""
    kw.setdefault("ionic", False)
    return kw


# ---------------------------------------------------------------------------
# INORGÁNICA
# ---------------------------------------------------------------------------

_INORGANICA: List[Dict] = [
    # ---------- ÓXIDOS METÁLICOS ----------
    _C(id="cao", name_es="oxido de calcio", name_display="Óxido de calcio",
       name_iupac="Óxido de calcio", formula="CaO", formula_display="CaO",
       smiles="[Ca]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="basico",
       nomenclature_note="Óxido del metal Ca(II). Nomenclatura de stock: óxido de calcio."),
    _C(id="fe2o3", name_es="oxido de hierro(III)", name_display="Óxido de hierro(III)",
       name_iupac="Trióxido de dihierro", formula="Fe2O3", formula_display="Fe₂O₃",
       smiles="O=[Fe]O[Fe]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Fe con valencia +3. Tradicional: óxido férrico."),
    _C(id="feo", name_es="oxido de hierro(II)", name_display="Óxido de hierro(II)",
       name_iupac="Monóxido de hierro", formula="FeO", formula_display="FeO",
       smiles="[Fe]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Fe con valencia +2. Tradicional: óxido ferroso."),
    _C(id="cu2o", name_es="oxido de cobre(I)", name_display="Óxido de cobre(I)",
       name_iupac="Óxido de dicobre", formula="Cu2O", formula_display="Cu₂O",
       smiles="[Cu]O[Cu]", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Cu con valencia +1. Tradicional: óxido cuproso."),
    _C(id="cuo", name_es="oxido de cobre(II)", name_display="Óxido de cobre(II)",
       name_iupac="Monóxido de cobre", formula="CuO", formula_display="CuO",
       smiles="[Cu]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Cu con valencia +2. Tradicional: óxido cúprico."),
    _C(id="na2o", name_es="oxido de sodio", name_display="Óxido de sodio",
       name_iupac="Óxido de disodio", formula="Na2O", formula_display="Na₂O",
       smiles="[Na]O[Na]", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="basico",
       nomenclature_note="Metal alcalino, valencia única +1."),
    _C(id="mgo", name_es="oxido de magnesio", name_display="Óxido de magnesio",
       name_iupac="Óxido de magnesio", formula="MgO", formula_display="MgO",
       smiles="[Mg]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="basico",
       nomenclature_note="Metal alcalinotérreo, valencia única +2."),
    _C(id="al2o3", name_es="oxido de aluminio", name_display="Óxido de aluminio",
       name_iupac="Trióxido de dialuminio", formula="Al2O3", formula_display="Al₂O₃",
       smiles="O=[Al]O[Al]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Al con valencia única +3."),
    _C(id="zno", name_es="oxido de zinc", name_display="Óxido de zinc",
       name_iupac="Óxido de zinc", formula="ZnO", formula_display="ZnO",
       smiles="[Zn]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="basico",
       nomenclature_note="Zn con valencia única +2."),
    _C(id="pbo", name_es="oxido de plomo(II)", name_display="Óxido de plomo(II)",
       name_iupac="Monóxido de plomo", formula="PbO", formula_display="PbO",
       smiles="[Pb]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Pb con valencia +2. Tradicional: óxido plumboso."),
    _C(id="pbo2", name_es="oxido de plomo(IV)", name_display="Óxido de plomo(IV)",
       name_iupac="Dióxido de plomo", formula="PbO2", formula_display="PbO₂",
       smiles="O=[Pb]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="avanzado",
       nomenclature_note="Pb con valencia +4. Tradicional: óxido plúmbico."),
    _C(id="cr2o3", name_es="oxido de cromo(III)", name_display="Óxido de cromo(III)",
       name_iupac="Trióxido de dicromo", formula="Cr2O3", formula_display="Cr₂O₃",
       smiles="O=[Cr]O[Cr]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="avanzado",
       nomenclature_note="Cr con valencia +3. Tradicional: óxido crómico."),
    _C(id="mno", name_es="oxido de manganeso(II)", name_display="Óxido de manganeso(II)",
       name_iupac="Monóxido de manganeso", formula="MnO", formula_display="MnO",
       smiles="[Mn]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Mn con valencia +2. Tradicional: óxido manganoso."),
    _C(id="mno2", name_es="oxido de manganeso(IV)", name_display="Óxido de manganeso(IV)",
       name_iupac="Dióxido de manganeso", formula="MnO2", formula_display="MnO₂",
       smiles="O=[Mn]=O", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="avanzado",
       nomenclature_note="Mn con valencia +4. Forma anfótera estable."),
    _C(id="ag2o", name_es="oxido de plata", name_display="Óxido de plata",
       name_iupac="Óxido de diplata", formula="Ag2O", formula_display="Ag₂O",
       smiles="[Ag]O[Ag]", category="inorganica",
       subcategory="oxidos_metalicos", subcategory_display="Óxidos metálicos",
       difficulty="intermedio",
       nomenclature_note="Ag con valencia única +1."),

    # ---------- ANHÍDRIDOS (óxidos no metálicos) ----------
    _C(id="so2", name_es="dioxido de azufre", name_display="Dióxido de azufre",
       name_iupac="Dióxido de azufre", formula="SO2", formula_display="SO₂",
       smiles="O=S=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="basico",
       nomenclature_note="S con valencia +4. Tradicional: anhídrido sulfuroso."),
    _C(id="so3", name_es="trioxido de azufre", name_display="Trióxido de azufre",
       name_iupac="Trióxido de azufre", formula="SO3", formula_display="SO₃",
       smiles="O=S(=O)=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="intermedio",
       nomenclature_note="S con valencia +6. Tradicional: anhídrido sulfúrico."),
    _C(id="co2", name_es="dioxido de carbono", name_display="Dióxido de carbono",
       name_iupac="Dióxido de carbono", formula="CO2", formula_display="CO₂",
       smiles="O=C=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="basico",
       nomenclature_note="C con valencia +4. Tradicional: anhídrido carbónico."),
    _C(id="co", name_es="monoxido de carbono", name_display="Monóxido de carbono",
       name_iupac="Monóxido de carbono", formula="CO", formula_display="CO",
       smiles="[C-]#[O+]", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="basico",
       nomenclature_note="C con valencia +2. Tradicional: anhídrido carbonoso."),
    _C(id="no", name_es="monoxido de nitrogeno", name_display="Monóxido de nitrógeno",
       name_iupac="Monóxido de nitrógeno", formula="NO", formula_display="NO",
       smiles="[N]=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="intermedio",
       nomenclature_note="N con valencia +2. Radical libre estable."),
    _C(id="no2", name_es="dioxido de nitrogeno", name_display="Dióxido de nitrógeno",
       name_iupac="Dióxido de nitrógeno", formula="NO2", formula_display="NO₂",
       smiles="O=[N]=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="intermedio", ionic=True,
       nomenclature_note="N con valencia +4. Radical libre; RDKit lo rinde como texto."),
    _C(id="n2o3", name_es="trioxido de dinitrogeno", name_display="Trióxido de dinitrógeno",
       name_iupac="Trióxido de dinitrógeno", formula="N2O3", formula_display="N₂O₃",
       smiles="O=NN=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="avanzado",
       nomenclature_note="N con valencia +3. Tradicional: anhídrido nitroso."),
    _C(id="n2o5", name_es="pentaoxido de dinitrogeno", name_display="Pentaóxido de dinitrógeno",
       name_iupac="Pentaóxido de dinitrógeno", formula="N2O5", formula_display="N₂O₅",
       smiles="O=N(=O)ON(=O)=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="avanzado",
       nomenclature_note="N con valencia +5. Tradicional: anhídrido nítrico."),
    _C(id="p2o3", name_es="trioxido de difosforo", name_display="Trióxido de difósforo",
       name_iupac="Trióxido de difósforo", formula="P2O3", formula_display="P₂O₃",
       smiles="O=POP=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="avanzado",
       nomenclature_note="P con valencia +3. Tradicional: anhídrido fosforoso."),
    _C(id="p2o5", name_es="pentaoxido de difosforo", name_display="Pentaóxido de difósforo",
       name_iupac="Pentaóxido de difósforo", formula="P2O5", formula_display="P₂O₅",
       smiles="O=P(=O)(OP(=O)=O)O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="avanzado", ionic=True,
       nomenclature_note="P con valencia +5. Tradicional: anhídrido fosfórico. Render como texto."),
    _C(id="sio2", name_es="dioxido de silicio", name_display="Dióxido de silicio",
       name_iupac="Dióxido de silicio", formula="SiO2", formula_display="SiO₂",
       smiles="O=[Si]=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="basico",
       nomenclature_note="Si con valencia +4. Sólido covalente, cuarzo."),
    _C(id="cl2o", name_es="oxido de dicloro", name_display="Óxido de dicloro",
       name_iupac="Monóxido de dicloro", formula="Cl2O", formula_display="Cl₂O",
       smiles="ClOCl", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="intermedio",
       nomenclature_note="Cl con valencia +1. Tradicional: anhídrido hipocloroso."),
    _C(id="cl2o7", name_es="heptaoxido de dicloro", name_display="Heptaóxido de dicloro",
       name_iupac="Heptaóxido de dicloro", formula="Cl2O7", formula_display="Cl₂O₇",
       smiles="O=Cl(=O)(=O)OCl(=O)(=O)=O", category="inorganica",
       subcategory="anhidridos", subcategory_display="Anhídridos",
       difficulty="avanzado",
       nomenclature_note="Cl con valencia +7. Tradicional: anhídrido perclórico."),

    # ---------- PERÓXIDOS ----------
    _C(id="h2o2", name_es="peroxido de hidrogeno", name_display="Peróxido de hidrógeno",
       name_iupac="Peróxido de hidrógeno", formula="H2O2", formula_display="H₂O₂",
       smiles="OO", category="inorganica",
       subcategory="peroxidos", subcategory_display="Peróxidos",
       difficulty="basico",
       nomenclature_note="Enlace O-O característico. Agua oxigenada."),
    _C(id="na2o2", name_es="peroxido de sodio", name_display="Peróxido de sodio",
       name_iupac="Peróxido de disodio", formula="Na2O2", formula_display="Na₂O₂",
       smiles="[Na]OO[Na]", category="inorganica",
       subcategory="peroxidos", subcategory_display="Peróxidos",
       difficulty="intermedio",
       nomenclature_note="Grupo peróxido O₂²⁻ con dos Na⁺."),
    _C(id="bao2", name_es="peroxido de bario", name_display="Peróxido de bario",
       name_iupac="Peróxido de bario", formula="BaO2", formula_display="BaO₂",
       smiles="[Ba]OO", category="inorganica",
       subcategory="peroxidos", subcategory_display="Peróxidos",
       difficulty="avanzado",
       nomenclature_note="Ba²⁺ con grupo peróxido O₂²⁻."),

    # ---------- HIDRUROS METÁLICOS ----------
    _C(id="nah", name_es="hidruro de sodio", name_display="Hidruro de sodio",
       name_iupac="Hidruro de sodio", formula="NaH", formula_display="NaH",
       smiles="[NaH]", category="inorganica",
       subcategory="hidruros_metalicos", subcategory_display="Hidruros metálicos",
       difficulty="basico",
       nomenclature_note="H actúa con valencia -1 (hidruro)."),
    _C(id="cah2", name_es="hidruro de calcio", name_display="Hidruro de calcio",
       name_iupac="Dihidruro de calcio", formula="CaH2", formula_display="CaH₂",
       smiles="[CaH2]", category="inorganica",
       subcategory="hidruros_metalicos", subcategory_display="Hidruros metálicos",
       difficulty="basico",
       nomenclature_note="Ca²⁺ con dos H⁻."),
    _C(id="mgh2", name_es="hidruro de magnesio", name_display="Hidruro de magnesio",
       name_iupac="Dihidruro de magnesio", formula="MgH2", formula_display="MgH₂",
       smiles="[MgH2]", category="inorganica",
       subcategory="hidruros_metalicos", subcategory_display="Hidruros metálicos",
       difficulty="basico",
       nomenclature_note="Mg²⁺ con dos H⁻."),
    _C(id="alh3", name_es="hidruro de aluminio", name_display="Hidruro de aluminio",
       name_iupac="Trihidruro de aluminio", formula="AlH3", formula_display="AlH₃",
       smiles="[AlH3]", category="inorganica",
       subcategory="hidruros_metalicos", subcategory_display="Hidruros metálicos",
       difficulty="intermedio",
       nomenclature_note="Al³⁺ con tres H⁻."),
    _C(id="lih", name_es="hidruro de litio", name_display="Hidruro de litio",
       name_iupac="Hidruro de litio", formula="LiH", formula_display="LiH",
       smiles="[LiH]", category="inorganica",
       subcategory="hidruros_metalicos", subcategory_display="Hidruros metálicos",
       difficulty="basico",
       nomenclature_note="Li⁺ con H⁻."),
    _C(id="kh", name_es="hidruro de potasio", name_display="Hidruro de potasio",
       name_iupac="Hidruro de potasio", formula="KH", formula_display="KH",
       smiles="[KH]", category="inorganica",
       subcategory="hidruros_metalicos", subcategory_display="Hidruros metálicos",
       difficulty="basico",
       nomenclature_note="K⁺ con H⁻."),

    # ---------- HIDRUROS VOLÁTILES ----------
    _C(id="nh3", name_es="amoniaco", name_display="Amoníaco",
       name_iupac="Trihidruro de nitrógeno", formula="NH3", formula_display="NH₃",
       smiles="N", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="Nombre común: amoníaco. H actúa con +1."),
    _C(id="ph3", name_es="fosfina", name_display="Fosfina",
       name_iupac="Trihidruro de fósforo", formula="PH3", formula_display="PH₃",
       smiles="[PH3]", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="intermedio",
       nomenclature_note="Nombre común: fosfina."),
    _C(id="h2s", name_es="sulfuro de hidrogeno", name_display="Sulfuro de hidrógeno",
       name_iupac="Sulfuro de dihidrógeno", formula="H2S", formula_display="H₂S",
       smiles="S", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="En disolución acuosa: ácido sulfhídrico."),
    _C(id="h2se", name_es="seleniuro de hidrogeno", name_display="Seleniuro de hidrógeno",
       name_iupac="Seleniuro de dihidrógeno", formula="H2Se", formula_display="H₂Se",
       smiles="[SeH2]", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="avanzado",
       nomenclature_note="Análogo del H₂S, más reactivo."),
    _C(id="hf_gas", name_es="fluoruro de hidrogeno", name_display="Fluoruro de hidrógeno",
       name_iupac="Fluoruro de hidrógeno", formula="HF", formula_display="HF",
       smiles="F", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="En estado gaseoso. En disolución: ácido fluorhídrico."),
    _C(id="hcl_gas", name_es="cloruro de hidrogeno", name_display="Cloruro de hidrógeno",
       name_iupac="Cloruro de hidrógeno", formula="HCl", formula_display="HCl",
       smiles="Cl", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="En estado gaseoso. En disolución: ácido clorhídrico."),
    _C(id="hbr_gas", name_es="bromuro de hidrogeno", name_display="Bromuro de hidrógeno",
       name_iupac="Bromuro de hidrógeno", formula="HBr", formula_display="HBr",
       smiles="Br", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="En estado gaseoso. En disolución: ácido bromhídrico."),
    _C(id="hi_gas", name_es="yoduro de hidrogeno", name_display="Yoduro de hidrógeno",
       name_iupac="Yoduro de hidrógeno", formula="HI", formula_display="HI",
       smiles="I", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="intermedio",
       nomenclature_note="En estado gaseoso. En disolución: ácido yodhídrico."),
    _C(id="h2o", name_es="agua", name_display="Agua",
       name_iupac="Óxido de dihidrógeno", formula="H2O", formula_display="H₂O",
       smiles="O", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="Hidruro de oxígeno. Nombre tradicional: agua."),
    _C(id="sih4", name_es="silano", name_display="Silano",
       name_iupac="Tetrahidruro de silicio", formula="SiH4", formula_display="SiH₄",
       smiles="[SiH4]", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="avanzado",
       nomenclature_note="Análogo inorgánico del metano (CH₄)."),
    _C(id="ch4", name_es="metano", name_display="Metano",
       name_iupac="Tetrahidruro de carbono", formula="CH4", formula_display="CH₄",
       smiles="C", category="inorganica",
       subcategory="hidruros_volatiles", subcategory_display="Hidruros volátiles",
       difficulty="basico",
       nomenclature_note="Hidruro de C. En orgánica se estudia como alcano."),

    # ---------- HIDRÁCIDOS (disoluciones acuosas) ----------
    _C(id="hfaq", name_es="acido fluorhidrico", name_display="Ácido fluorhídrico",
       name_iupac="Fluoruro de hidrógeno (ac.)", formula="HF(aq)",
       formula_display="HF(aq)", smiles="F", category="inorganica",
       subcategory="hidracidos", subcategory_display="Hidrácidos",
       difficulty="basico", ionic=True,
       nomenclature_note="Disolución acuosa del HF. Ataca el vidrio."),
    _C(id="hclaq", name_es="acido clorhidrico", name_display="Ácido clorhídrico",
       name_iupac="Cloruro de hidrógeno (ac.)", formula="HCl(aq)",
       formula_display="HCl(aq)", smiles="Cl", category="inorganica",
       subcategory="hidracidos", subcategory_display="Hidrácidos",
       difficulty="basico", ionic=True,
       nomenclature_note="Ácido fuerte de uso muy común."),
    _C(id="hbraq", name_es="acido bromhidrico", name_display="Ácido bromhídrico",
       name_iupac="Bromuro de hidrógeno (ac.)", formula="HBr(aq)",
       formula_display="HBr(aq)", smiles="Br", category="inorganica",
       subcategory="hidracidos", subcategory_display="Hidrácidos",
       difficulty="basico", ionic=True,
       nomenclature_note="Ácido fuerte, similar al HCl."),
    _C(id="hiaq", name_es="acido yodhidrico", name_display="Ácido yodhídrico",
       name_iupac="Yoduro de hidrógeno (ac.)", formula="HI(aq)",
       formula_display="HI(aq)", smiles="I", category="inorganica",
       subcategory="hidracidos", subcategory_display="Hidrácidos",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Ácido fuerte."),
    _C(id="h2saq", name_es="acido sulfhidrico", name_display="Ácido sulfhídrico",
       name_iupac="Sulfuro de dihidrógeno (ac.)", formula="H2S(aq)",
       formula_display="H₂S(aq)", smiles="S", category="inorganica",
       subcategory="hidracidos", subcategory_display="Hidrácidos",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Ácido débil, olor a huevos podridos."),
    _C(id="hcn", name_es="acido cianhidrico", name_display="Ácido cianhídrico",
       name_iupac="Cianuro de hidrógeno", formula="HCN", formula_display="HCN",
       smiles="C#N", category="inorganica",
       subcategory="hidracidos", subcategory_display="Hidrácidos",
       difficulty="avanzado", ionic=True,
       nomenclature_note="Excepción: contiene C pero se trata como hidrácido."),

    # ---------- SALES NEUTRAS ----------
    _C(id="nacl", name_es="cloruro de sodio", name_display="Cloruro de sodio",
       name_iupac="Cloruro de sodio", formula="NaCl", formula_display="NaCl",
       smiles="[Na+].[Cl-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="basico", ionic=True,
       nomenclature_note="Sal de mesa. Sal binaria metal/no metal."),
    _C(id="kbr", name_es="bromuro de potasio", name_display="Bromuro de potasio",
       name_iupac="Bromuro de potasio", formula="KBr", formula_display="KBr",
       smiles="[K+].[Br-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="basico", ionic=True,
       nomenclature_note="Sal binaria."),
    _C(id="caf2", name_es="fluoruro de calcio", name_display="Fluoruro de calcio",
       name_iupac="Difluoruro de calcio", formula="CaF2", formula_display="CaF₂",
       smiles="[Ca+2].[F-].[F-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Fluorita. Ca²⁺ con dos F⁻."),
    _C(id="mgcl2", name_es="cloruro de magnesio", name_display="Cloruro de magnesio",
       name_iupac="Dicloruro de magnesio", formula="MgCl2", formula_display="MgCl₂",
       smiles="[Mg+2].[Cl-].[Cl-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Mg²⁺ con dos Cl⁻."),
    _C(id="fecl3", name_es="cloruro de hierro(III)", name_display="Cloruro de hierro(III)",
       name_iupac="Tricloruro de hierro", formula="FeCl3", formula_display="FeCl₃",
       smiles="[Fe+3].[Cl-].[Cl-].[Cl-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="avanzado", ionic=True,
       nomenclature_note="Fe con valencia +3. Tradicional: cloruro férrico."),
    _C(id="alcl3", name_es="cloruro de aluminio", name_display="Cloruro de aluminio",
       name_iupac="Tricloruro de aluminio", formula="AlCl3", formula_display="AlCl₃",
       smiles="[Al+3].[Cl-].[Cl-].[Cl-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Al³⁺ con tres Cl⁻."),
    _C(id="agcl", name_es="cloruro de plata", name_display="Cloruro de plata",
       name_iupac="Cloruro de plata", formula="AgCl", formula_display="AgCl",
       smiles="[Ag+].[Cl-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Precipitado blanco insoluble."),
    _C(id="zncl2", name_es="cloruro de zinc", name_display="Cloruro de zinc",
       name_iupac="Dicloruro de zinc", formula="ZnCl2", formula_display="ZnCl₂",
       smiles="[Zn+2].[Cl-].[Cl-]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Zn²⁺ con dos Cl⁻."),
    _C(id="na2s", name_es="sulfuro de sodio", name_display="Sulfuro de sodio",
       name_iupac="Sulfuro de disodio", formula="Na2S", formula_display="Na₂S",
       smiles="[Na+].[Na+].[S-2]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Dos Na⁺ con S²⁻."),
    _C(id="fes", name_es="sulfuro de hierro(II)", name_display="Sulfuro de hierro(II)",
       name_iupac="Sulfuro de hierro", formula="FeS", formula_display="FeS",
       smiles="[Fe+2].[S-2]", category="inorganica",
       subcategory="sales_neutras", subcategory_display="Sales neutras",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Fe²⁺ con S²⁻. Tradicional: sulfuro ferroso."),

    # ---------- SALES VOLÁTILES ----------
    _C(id="nh4cl", name_es="cloruro de amonio", name_display="Cloruro de amonio",
       name_iupac="Cloruro de amonio", formula="NH4Cl", formula_display="NH₄Cl",
       smiles="[NH4+].[Cl-]", category="inorganica",
       subcategory="sales_volatiles", subcategory_display="Sales volátiles",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Catión amonio NH₄⁺ con Cl⁻."),
    _C(id="nh4br", name_es="bromuro de amonio", name_display="Bromuro de amonio",
       name_iupac="Bromuro de amonio", formula="NH4Br", formula_display="NH₄Br",
       smiles="[NH4+].[Br-]", category="inorganica",
       subcategory="sales_volatiles", subcategory_display="Sales volátiles",
       difficulty="intermedio", ionic=True,
       nomenclature_note="Catión amonio NH₄⁺ con Br⁻."),

    # ---------- HIDRÓXIDOS ----------
    _C(id="naoh", name_es="hidroxido de sodio", name_display="Hidróxido de sodio",
       name_iupac="Hidróxido de sodio", formula="NaOH", formula_display="NaOH",
       smiles="[Na+].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="basico",
       nomenclature_note="Base fuerte. Sosa cáustica."),
    _C(id="koh", name_es="hidroxido de potasio", name_display="Hidróxido de potasio",
       name_iupac="Hidróxido de potasio", formula="KOH", formula_display="KOH",
       smiles="[K+].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="basico",
       nomenclature_note="Base fuerte. Potasa cáustica."),
    _C(id="caoh2", name_es="hidroxido de calcio", name_display="Hidróxido de calcio",
       name_iupac="Dihidróxido de calcio", formula="Ca(OH)2", formula_display="Ca(OH)₂",
       smiles="[Ca+2].[OH-].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="basico",
       nomenclature_note="Cal apagada."),
    _C(id="mgoh2", name_es="hidroxido de magnesio", name_display="Hidróxido de magnesio",
       name_iupac="Dihidróxido de magnesio", formula="Mg(OH)2", formula_display="Mg(OH)₂",
       smiles="[Mg+2].[OH-].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="basico",
       nomenclature_note="Mg²⁺ con dos OH⁻. Leche de magnesia."),
    _C(id="aloh3", name_es="hidroxido de aluminio", name_display="Hidróxido de aluminio",
       name_iupac="Trihidróxido de aluminio", formula="Al(OH)3",
       formula_display="Al(OH)₃", smiles="[Al+3].[OH-].[OH-].[OH-]",
       category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="intermedio",
       nomenclature_note="Anfótero: reacciona con ácidos y bases."),
    _C(id="feoh2", name_es="hidroxido de hierro(II)", name_display="Hidróxido de hierro(II)",
       name_iupac="Dihidróxido de hierro", formula="Fe(OH)2",
       formula_display="Fe(OH)₂", smiles="[Fe+2].[OH-].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="intermedio",
       nomenclature_note="Fe con valencia +2. Tradicional: hidróxido ferroso."),
    _C(id="feoh3", name_es="hidroxido de hierro(III)", name_display="Hidróxido de hierro(III)",
       name_iupac="Trihidróxido de hierro", formula="Fe(OH)3",
       formula_display="Fe(OH)₃", smiles="[Fe+3].[OH-].[OH-].[OH-]",
       category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="avanzado",
       nomenclature_note="Fe con valencia +3. Color rojizo (óxido de hierro hidratado)."),
    _C(id="cuoh2", name_es="hidroxido de cobre(II)", name_display="Hidróxido de cobre(II)",
       name_iupac="Dihidróxido de cobre", formula="Cu(OH)2",
       formula_display="Cu(OH)₂", smiles="[Cu+2].[OH-].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="intermedio",
       nomenclature_note="Precipitado azul característico."),
    _C(id="baoh2", name_es="hidroxido de bario", name_display="Hidróxido de bario",
       name_iupac="Dihidróxido de bario", formula="Ba(OH)2",
       formula_display="Ba(OH)₂", smiles="[Ba+2].[OH-].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="intermedio",
       nomenclature_note="Base fuerte. Ba²⁺ con dos OH⁻."),
    _C(id="znoh2", name_es="hidroxido de zinc", name_display="Hidróxido de zinc",
       name_iupac="Dihidróxido de zinc", formula="Zn(OH)2",
       formula_display="Zn(OH)₂", smiles="[Zn+2].[OH-].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="intermedio",
       nomenclature_note="Anfótero."),
    _C(id="nh4oh", name_es="hidroxido de amonio", name_display="Hidróxido de amonio",
       name_iupac="Hidróxido de amonio", formula="NH4OH",
       formula_display="NH₄OH", smiles="[NH4+].[OH-]", category="inorganica",
       subcategory="hidroxidos", subcategory_display="Hidróxidos",
       difficulty="basico",
       nomenclature_note="Disolución acuosa de amoníaco."),

    # ---------- OXOÁCIDOS ----------
    _C(id="h2so4", name_es="acido sulfurico", name_display="Ácido sulfúrico",
       name_iupac="Tetraoxosulfato(VI) de dihidrógeno", formula="H2SO4",
       formula_display="H₂SO₄", smiles="OS(=O)(=O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="intermedio",
       nomenclature_note="S con valencia +6. Ácido fuerte muy importante."),
    _C(id="h2so3", name_es="acido sulfuroso", name_display="Ácido sulfuroso",
       name_iupac="Trioxosulfato(IV) de dihidrógeno", formula="H2SO3",
       formula_display="H₂SO₃", smiles="OS(=O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="intermedio",
       nomenclature_note="S con valencia +4."),
    _C(id="hno3", name_es="acido nitrico", name_display="Ácido nítrico",
       name_iupac="Trioxonitrato(V) de hidrógeno", formula="HNO3",
       formula_display="HNO₃", smiles="O[N+](=O)[O-]", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="basico",
       nomenclature_note="N con valencia +5. Ácido fuerte oxidante."),
    _C(id="hno2", name_es="acido nitroso", name_display="Ácido nitroso",
       name_iupac="Dioxonitrato(III) de hidrógeno", formula="HNO2",
       formula_display="HNO₂", smiles="ON=O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="intermedio",
       nomenclature_note="N con valencia +3."),
    _C(id="h3po4", name_es="acido fosforico", name_display="Ácido fosfórico",
       name_iupac="Tetraoxofosfato(V) de trihidrógeno", formula="H3PO4",
       formula_display="H₃PO₄", smiles="OP(=O)(O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="intermedio",
       nomenclature_note="P con valencia +5. Ácido triprótico."),
    _C(id="h3po3", name_es="acido fosforoso", name_display="Ácido fosforoso",
       name_iupac="Trioxofosfato(III) de trihidrógeno", formula="H3PO3",
       formula_display="H₃PO₃", smiles="OP(O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="P con valencia +3."),
    _C(id="h2co3", name_es="acido carbonico", name_display="Ácido carbónico",
       name_iupac="Trioxocarbonato(IV) de dihidrógeno", formula="H2CO3",
       formula_display="H₂CO₃", smiles="OC(=O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="basico",
       nomenclature_note="C con valencia +4. Inestable, se descompone en CO₂ + H₂O."),
    _C(id="hclo", name_es="acido hipocloroso", name_display="Ácido hipocloroso",
       name_iupac="Oxoclorato(I) de hidrógeno", formula="HClO",
       formula_display="HClO", smiles="ClO", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="intermedio",
       nomenclature_note="Cl con valencia +1. Prefijo hipo-, sufijo -oso."),
    _C(id="hclo2", name_es="acido cloroso", name_display="Ácido cloroso",
       name_iupac="Dioxoclorato(III) de hidrógeno", formula="HClO2",
       formula_display="HClO₂", smiles="OCl=O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="Cl con valencia +3. Sufijo -oso."),
    _C(id="hclo3", name_es="acido clorico", name_display="Ácido clórico",
       name_iupac="Trioxoclorato(V) de hidrógeno", formula="HClO3",
       formula_display="HClO₃", smiles="OCl(=O)=O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="Cl con valencia +5. Sufijo -ico."),
    _C(id="hclo4", name_es="acido perclorico", name_display="Ácido perclórico",
       name_iupac="Tetraoxoclorato(VII) de hidrógeno", formula="HClO4",
       formula_display="HClO₄", smiles="OCl(=O)(=O)=O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="Cl con valencia +7. Prefijo per-, sufijo -ico."),
    _C(id="h2sio3", name_es="acido silicico", name_display="Ácido silícico",
       name_iupac="Trioxosilicato(IV) de dihidrógeno", formula="H2SiO3",
       formula_display="H₂SiO₃", smiles="O[Si](=O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="Si con valencia +4."),
    _C(id="h3bo3", name_es="acido borico", name_display="Ácido bórico",
       name_iupac="Trioxoborato(III) de trihidrógeno", formula="H3BO3",
       formula_display="H₃BO₃", smiles="OB(O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="B con valencia +3. Ácido débil."),
    _C(id="hmno4", name_es="acido permanganico", name_display="Ácido permangánico",
       name_iupac="Tetraoxomanganato(VII) de hidrógeno", formula="HMnO4",
       formula_display="HMnO₄", smiles="O[Mn](=O)(=O)=O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="Mn con valencia +7. Oxidante muy fuerte."),
    _C(id="h2cro4", name_es="acido cromico", name_display="Ácido crómico",
       name_iupac="Tetraoxocromato(VI) de dihidrógeno", formula="H2CrO4",
       formula_display="H₂CrO₄", smiles="O[Cr](=O)(=O)O", category="inorganica",
       subcategory="oxoacidos", subcategory_display="Oxoácidos",
       difficulty="avanzado",
       nomenclature_note="Cr con valencia +6. Oxidante."),

    # ---------- OXISALES ----------
    _C(id="na2so4", name_es="sulfato de sodio", name_display="Sulfato de sodio",
       name_iupac="Tetraoxosulfato(VI) de disodio", formula="Na2SO4",
       formula_display="Na₂SO₄", smiles="[Na+].[Na+].[O-]S(=O)(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="basico", ionic=True,
       nomenclature_note="Sal del ácido sulfúrico. Anión SO₄²⁻."),
    _C(id="caso4", name_es="sulfato de calcio", name_display="Sulfato de calcio",
       name_iupac="Tetraoxosulfato(VI) de calcio", formula="CaSO4",
       formula_display="CaSO₄", smiles="[Ca+2].[O-]S(=O)(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="basico", ionic=True,
       nomenclature_note="Yeso (hidratado)."),
    _C(id="mgso4", name_es="sulfato de magnesio", name_display="Sulfato de magnesio",
       name_iupac="Tetraoxosulfato(VI) de magnesio", formula="MgSO4",
       formula_display="MgSO₄", smiles="[Mg+2].[O-]S(=O)(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="intermedio", ionic=True,
       nomenclature_note="Sal de Epsom (hidratado)."),
    _C(id="cuso4", name_es="sulfato de cobre(II)", name_display="Sulfato de cobre(II)",
       name_iupac="Tetraoxosulfato(VI) de cobre", formula="CuSO4",
       formula_display="CuSO₄", smiles="[Cu+2].[O-]S(=O)(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="intermedio", ionic=True,
       nomenclature_note="Pentahidratado es azul intenso."),
    _C(id="nano3", name_es="nitrato de sodio", name_display="Nitrato de sodio",
       name_iupac="Trioxonitrato(V) de sodio", formula="NaNO3",
       formula_display="NaNO₃", smiles="[Na+].[O-][N+](=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="basico", ionic=True,
       nomenclature_note="Sal del ácido nítrico. Salitre de Chile."),
    _C(id="kno3", name_es="nitrato de potasio", name_display="Nitrato de potasio",
       name_iupac="Trioxonitrato(V) de potasio", formula="KNO3",
       formula_display="KNO₃", smiles="[K+].[O-][N+](=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="basico", ionic=True,
       nomenclature_note="Salitre. Componente de la pólvora."),
    _C(id="agno3", name_es="nitrato de plata", name_display="Nitrato de plata",
       name_iupac="Trioxonitrato(V) de plata", formula="AgNO3",
       formula_display="AgNO₃", smiles="[Ag+].[O-][N+](=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="intermedio", ionic=True,
       nomenclature_note="Reactivo común. Mancha negra al reducirse."),
    _C(id="caco3", name_es="carbonato de calcio", name_display="Carbonato de calcio",
       name_iupac="Trioxocarbonato(IV) de calcio", formula="CaCO3",
       formula_display="CaCO₃", smiles="[Ca+2].[O-]C(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="basico", ionic=True,
       nomenclature_note="Caliza, mármol. Anión CO₃²⁻."),
    _C(id="na2co3", name_es="carbonato de sodio", name_display="Carbonato de sodio",
       name_iupac="Trioxocarbonato(IV) de disodio", formula="Na2CO3",
       formula_display="Na₂CO₃", smiles="[Na+].[Na+].[O-]C(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="basico", ionic=True,
       nomenclature_note="Sosa Solvay."),
    _C(id="nahco3", name_es="bicarbonato de sodio", name_display="Bicarbonato de sodio",
       name_iupac="Hidrógenotrioxocarbonato(IV) de sodio", formula="NaHCO3",
       formula_display="NaHCO₃", smiles="[Na+].OC(=O)[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="intermedio", ionic=True,
       nomenclature_note="Sal ácida (queda un H del ácido). Bicarbonato."),
    _C(id="ca3po42", name_es="fosfato de calcio", name_display="Fosfato de calcio",
       name_iupac="Bis(tetraoxofosfato(V)) de tricalcio",
       formula="Ca3(PO4)2", formula_display="Ca₃(PO₄)₂",
       smiles="[Ca+2].[Ca+2].[Ca+2].[O-]P(=O)([O-])[O-].[O-]P(=O)([O-])[O-]",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="avanzado", ionic=True,
       nomenclature_note="Componente principal de los huesos."),
    _C(id="kmno4", name_es="permanganato de potasio", name_display="Permanganato de potasio",
       name_iupac="Tetraoxomanganato(VII) de potasio", formula="KMnO4",
       formula_display="KMnO₄", smiles="[K+].[O-][Mn](=O)(=O)=O",
       category="inorganica", subcategory="oxisales",
       subcategory_display="Oxisales", difficulty="avanzado", ionic=True,
       nomenclature_note="Oxidante fuerte. Color violeta."),
]


# ---------------------------------------------------------------------------
# ORGÁNICA
# ---------------------------------------------------------------------------

_ORGANICA: List[Dict] = [
    # ---------- ALCANOS ----------
    _C(id="metano", name_es="metano", name_display="Metano",
       name_iupac="Metano", formula="CH4", formula_display="CH₄",
       smiles="C", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="basico",
       nomenclature_note="C1. Hidrocarburo saturado más simple."),
    _C(id="etano", name_es="etano", name_display="Etano",
       name_iupac="Etano", formula="C2H6", formula_display="C₂H₆",
       smiles="CC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="basico",
       nomenclature_note="C2. CₙH₂ₙ₊₂."),
    _C(id="propano", name_es="propano", name_display="Propano",
       name_iupac="Propano", formula="C3H8", formula_display="C₃H₈",
       smiles="CCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="basico",
       nomenclature_note="C3. Gas de uso doméstico."),
    _C(id="butano", name_es="butano", name_display="Butano",
       name_iupac="Butano", formula="C4H10", formula_display="C₄H₁₀",
       smiles="CCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="basico",
       nomenclature_note="C4. Gas de uso doméstico."),
    _C(id="pentano", name_es="pentano", name_display="Pentano",
       name_iupac="Pentano", formula="C5H12", formula_display="C₅H₁₂",
       smiles="CCCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="basico",
       nomenclature_note="C5. Líquido volátil."),
    _C(id="hexano", name_es="hexano", name_display="Hexano",
       name_iupac="Hexano", formula="C6H14", formula_display="C₆H₁₄",
       smiles="CCCCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="intermedio",
       nomenclature_note="C6. Disolvente apolar común."),
    _C(id="heptano", name_es="heptano", name_display="Heptano",
       name_iupac="Heptano", formula="C7H16", formula_display="C₇H₁₆",
       smiles="CCCCCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="intermedio",
       nomenclature_note="C7. Componente de gasolinas."),
    _C(id="octano", name_es="octano", name_display="Octano",
       name_iupac="Octano", formula="C8H18", formula_display="C₈H₁₈",
       smiles="CCCCCCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="intermedio",
       nomenclature_note="C8. Referencia del índice de octano."),
    _C(id="nonano", name_es="nonano", name_display="Nonano",
       name_iupac="Nonano", formula="C9H20", formula_display="C₉H₂₀",
       smiles="CCCCCCCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="avanzado",
       nomenclature_note="C9."),
    _C(id="decano", name_es="decano", name_display="Decano",
       name_iupac="Decano", formula="C10H22", formula_display="C₁₀H₂₂",
       smiles="CCCCCCCCCC", category="organica",
       subcategory="alcanos", subcategory_display="Alcanos",
       difficulty="avanzado",
       nomenclature_note="C10."),

    # ---------- ALQUENOS ----------
    _C(id="eteno", name_es="eteno", name_display="Eteno",
       name_iupac="Eteno (etileno)", formula="C2H4", formula_display="C₂H₄",
       smiles="C=C", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="basico",
       nomenclature_note="Doble enlace C=C. Nombre común: etileno."),
    _C(id="propeno", name_es="propeno", name_display="Propeno",
       name_iupac="Prop-1-eno", formula="C3H6", formula_display="C₃H₆",
       smiles="C=CC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="basico",
       nomenclature_note="Doble enlace en C1. Propileno."),
    _C(id="but1eno", name_es="but-1-eno", name_display="But-1-eno",
       name_iupac="But-1-eno", formula="C4H8", formula_display="C₄H₈",
       smiles="C=CCC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="intermedio",
       nomenclature_note="Doble enlace en posición 1."),
    _C(id="but2eno", name_es="but-2-eno", name_display="But-2-eno",
       name_iupac="But-2-eno", formula="C4H8", formula_display="C₄H₈",
       smiles="CC=CC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="intermedio",
       nomenclature_note="Doble enlace en posición 2. Isómero del but-1-eno."),
    _C(id="pent1eno", name_es="pent-1-eno", name_display="Pent-1-eno",
       name_iupac="Pent-1-eno", formula="C5H10", formula_display="C₅H₁₀",
       smiles="C=CCCC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="intermedio",
       nomenclature_note="Doble enlace en C1."),
    _C(id="hex1eno", name_es="hex-1-eno", name_display="Hex-1-eno",
       name_iupac="Hex-1-eno", formula="C6H12", formula_display="C₆H₁₂",
       smiles="C=CCCCC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="avanzado",
       nomenclature_note="Doble enlace en C1."),
    _C(id="hept1eno", name_es="hept-1-eno", name_display="Hept-1-eno",
       name_iupac="Hept-1-eno", formula="C7H14", formula_display="C₇H₁₄",
       smiles="C=CCCCCC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="avanzado",
       nomenclature_note="Doble enlace en C1."),
    _C(id="oct1eno", name_es="oct-1-eno", name_display="Oct-1-eno",
       name_iupac="Oct-1-eno", formula="C8H16", formula_display="C₈H₁₆",
       smiles="C=CCCCCCC", category="organica",
       subcategory="alquenos", subcategory_display="Alquenos",
       difficulty="avanzado",
       nomenclature_note="Doble enlace en C1."),

    # ---------- ALQUINOS ----------
    _C(id="etino", name_es="etino", name_display="Etino",
       name_iupac="Etino (acetileno)", formula="C2H2", formula_display="C₂H₂",
       smiles="C#C", category="organica",
       subcategory="alquinos", subcategory_display="Alquinos",
       difficulty="basico",
       nomenclature_note="Triple enlace C≡C. Nombre común: acetileno."),
    _C(id="propino", name_es="propino", name_display="Propino",
       name_iupac="Prop-1-ino", formula="C3H4", formula_display="C₃H₄",
       smiles="C#CC", category="organica",
       subcategory="alquinos", subcategory_display="Alquinos",
       difficulty="intermedio",
       nomenclature_note="Triple enlace en C1."),
    _C(id="but1ino", name_es="but-1-ino", name_display="But-1-ino",
       name_iupac="But-1-ino", formula="C4H6", formula_display="C₄H₆",
       smiles="C#CCC", category="organica",
       subcategory="alquinos", subcategory_display="Alquinos",
       difficulty="intermedio",
       nomenclature_note="Triple enlace en C1."),
    _C(id="pent1ino", name_es="pent-1-ino", name_display="Pent-1-ino",
       name_iupac="Pent-1-ino", formula="C5H8", formula_display="C₅H₈",
       smiles="C#CCCC", category="organica",
       subcategory="alquinos", subcategory_display="Alquinos",
       difficulty="avanzado",
       nomenclature_note="Triple enlace en C1."),
    _C(id="hex1ino", name_es="hex-1-ino", name_display="Hex-1-ino",
       name_iupac="Hex-1-ino", formula="C6H10", formula_display="C₆H₁₀",
       smiles="C#CCCCC", category="organica",
       subcategory="alquinos", subcategory_display="Alquinos",
       difficulty="avanzado",
       nomenclature_note="Triple enlace en C1."),

    # ---------- CICLOALCANOS ----------
    _C(id="ciclopropano", name_es="ciclopropano", name_display="Ciclopropano",
       name_iupac="Ciclopropano", formula="C3H6", formula_display="C₃H₆",
       smiles="C1CC1", category="organica",
       subcategory="cicloalcanos", subcategory_display="Cicloalcanos",
       difficulty="basico",
       nomenclature_note="Anillo de 3 carbonos. Muy tensionado."),
    _C(id="ciclobutano", name_es="ciclobutano", name_display="Ciclobutano",
       name_iupac="Ciclobutano", formula="C4H8", formula_display="C₄H₈",
       smiles="C1CCC1", category="organica",
       subcategory="cicloalcanos", subcategory_display="Cicloalcanos",
       difficulty="basico",
       nomenclature_note="Anillo de 4 carbonos."),
    _C(id="ciclopentano", name_es="ciclopentano", name_display="Ciclopentano",
       name_iupac="Ciclopentano", formula="C5H10", formula_display="C₅H₁₀",
       smiles="C1CCCC1", category="organica",
       subcategory="cicloalcanos", subcategory_display="Cicloalcanos",
       difficulty="intermedio",
       nomenclature_note="Anillo de 5 carbonos."),
    _C(id="ciclohexano", name_es="ciclohexano", name_display="Ciclohexano",
       name_iupac="Ciclohexano", formula="C6H12", formula_display="C₆H₁₂",
       smiles="C1CCCCC1", category="organica",
       subcategory="cicloalcanos", subcategory_display="Cicloalcanos",
       difficulty="intermedio",
       nomenclature_note="Anillo de 6 C. Conformación silla."),
    _C(id="cicloheptano", name_es="cicloheptano", name_display="Cicloheptano",
       name_iupac="Cicloheptano", formula="C7H14", formula_display="C₇H₁₄",
       smiles="C1CCCCCC1", category="organica",
       subcategory="cicloalcanos", subcategory_display="Cicloalcanos",
       difficulty="avanzado",
       nomenclature_note="Anillo de 7 carbonos."),

    # ---------- CICLOALQUENOS ----------
    _C(id="ciclobuteno", name_es="ciclobuteno", name_display="Ciclobuteno",
       name_iupac="Ciclobut-1-eno", formula="C4H6", formula_display="C₄H₆",
       smiles="C1=CCC1", category="organica",
       subcategory="cicloalquenos", subcategory_display="Cicloalquenos",
       difficulty="intermedio",
       nomenclature_note="Anillo de 4 C con un doble enlace."),
    _C(id="ciclopenteno", name_es="ciclopenteno", name_display="Ciclopenteno",
       name_iupac="Ciclopent-1-eno", formula="C5H8", formula_display="C₅H₈",
       smiles="C1=CCCC1", category="organica",
       subcategory="cicloalquenos", subcategory_display="Cicloalquenos",
       difficulty="intermedio",
       nomenclature_note="Anillo de 5 C con un doble enlace."),
    _C(id="ciclohexeno", name_es="ciclohexeno", name_display="Ciclohexeno",
       name_iupac="Ciclohex-1-eno", formula="C6H10", formula_display="C₆H₁₀",
       smiles="C1=CCCCC1", category="organica",
       subcategory="cicloalquenos", subcategory_display="Cicloalquenos",
       difficulty="avanzado",
       nomenclature_note="Anillo de 6 C con un doble enlace."),

    # ---------- AROMÁTICOS ----------
    _C(id="benceno", name_es="benceno", name_display="Benceno",
       name_iupac="Benceno", formula="C6H6", formula_display="C₆H₆",
       smiles="c1ccccc1", category="organica",
       subcategory="aromaticos", subcategory_display="Aromáticos",
       difficulty="intermedio",
       nomenclature_note="Anillo aromático. Resonancia de electrones π."),
    _C(id="tolueno", name_es="tolueno", name_display="Tolueno",
       name_iupac="Metilbenceno", formula="C7H8", formula_display="C₇H₈",
       smiles="Cc1ccccc1", category="organica",
       subcategory="aromaticos", subcategory_display="Aromáticos",
       difficulty="intermedio",
       nomenclature_note="Benceno con un grupo metilo."),
    _C(id="oxileno", name_es="o-xileno", name_display="o-Xileno",
       name_iupac="1,2-dimetilbenceno", formula="C8H10", formula_display="C₈H₁₀",
       smiles="Cc1ccccc1C", category="organica",
       subcategory="aromaticos", subcategory_display="Aromáticos",
       difficulty="avanzado",
       nomenclature_note="Dos metilos en posiciones contiguas (orto)."),
    _C(id="pxileno", name_es="p-xileno", name_display="p-Xileno",
       name_iupac="1,4-dimetilbenceno", formula="C8H10", formula_display="C₈H₁₀",
       smiles="Cc1ccc(C)cc1", category="organica",
       subcategory="aromaticos", subcategory_display="Aromáticos",
       difficulty="avanzado",
       nomenclature_note="Dos metilos opuestos (para)."),
    _C(id="mxileno", name_es="m-xileno", name_display="m-Xileno",
       name_iupac="1,3-dimetilbenceno", formula="C8H10", formula_display="C₈H₁₀",
       smiles="Cc1cccc(C)c1", category="organica",
       subcategory="aromaticos", subcategory_display="Aromáticos",
       difficulty="avanzado",
       nomenclature_note="Dos metilos separados por uno (meta)."),
    _C(id="naftaleno", name_es="naftaleno", name_display="Naftaleno",
       name_iupac="Naftaleno", formula="C10H8", formula_display="C₁₀H₈",
       smiles="c1ccc2ccccc2c1", category="organica",
       subcategory="aromaticos", subcategory_display="Aromáticos",
       difficulty="avanzado",
       nomenclature_note="Dos anillos bencénicos fusionados."),

    # ---------- HALOGENUROS ----------
    _C(id="clorometano", name_es="clorometano", name_display="Clorometano",
       name_iupac="Clorometano", formula="CH3Cl", formula_display="CH₃Cl",
       smiles="CCl", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="basico",
       nomenclature_note="Un H del metano sustituido por Cl."),
    _C(id="diclorometano", name_es="diclorometano", name_display="Diclorometano",
       name_iupac="Diclorometano", formula="CH2Cl2", formula_display="CH₂Cl₂",
       smiles="ClCCl", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="intermedio",
       nomenclature_note="Dos H del metano sustituidos por Cl."),
    _C(id="cloroformo", name_es="cloroformo", name_display="Cloroformo",
       name_iupac="Triclorometano", formula="CHCl3", formula_display="CHCl₃",
       smiles="ClC(Cl)Cl", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="intermedio",
       nomenclature_note="Tres H del metano sustituidos por Cl."),
    _C(id="tetraclorom", name_es="tetraclorometano", name_display="Tetraclorometano",
       name_iupac="Tetraclorometano", formula="CCl4", formula_display="CCl₄",
       smiles="ClC(Cl)(Cl)Cl", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="intermedio",
       nomenclature_note="Todos los H del metano sustituidos por Cl."),
    _C(id="cloroetano", name_es="cloroetano", name_display="Cloroetano",
       name_iupac="Cloroetano", formula="C2H5Cl", formula_display="C₂H₅Cl",
       smiles="CCCl", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="basico",
       nomenclature_note="Etano con un Cl."),
    _C(id="bromometano", name_es="bromometano", name_display="Bromometano",
       name_iupac="Bromometano", formula="CH3Br", formula_display="CH₃Br",
       smiles="CBr", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="basico",
       nomenclature_note="Metano con un Br."),
    _C(id="clorobenceno", name_es="clorobenceno", name_display="Clorobenceno",
       name_iupac="Clorobenceno", formula="C6H5Cl", formula_display="C₆H₅Cl",
       smiles="Clc1ccccc1", category="organica",
       subcategory="halogenuros", subcategory_display="Derivados halogenados",
       difficulty="avanzado",
       nomenclature_note="Benceno con un Cl como sustituyente."),

    # ---------- ALCOHOLES ----------
    _C(id="metanol", name_es="metanol", name_display="Metanol",
       name_iupac="Metanol", formula="CH3OH", formula_display="CH₃OH",
       smiles="CO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="basico",
       nomenclature_note="Grupo funcional -OH. Sufijo -ol."),
    _C(id="etanol", name_es="etanol", name_display="Etanol",
       name_iupac="Etanol", formula="C2H5OH", formula_display="C₂H₅OH",
       smiles="CCO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="basico",
       nomenclature_note="Alcohol del vino. C2H5-OH."),
    _C(id="propan1ol", name_es="propan-1-ol", name_display="Propan-1-ol",
       name_iupac="Propan-1-ol", formula="C3H7OH", formula_display="C₃H₇OH",
       smiles="CCCO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="basico",
       nomenclature_note="OH en C1. Alcohol primario."),
    _C(id="propan2ol", name_es="propan-2-ol", name_display="Propan-2-ol",
       name_iupac="Propan-2-ol", formula="C3H7OH", formula_display="C₃H₇OH",
       smiles="CC(O)C", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="intermedio",
       nomenclature_note="OH en C2. Alcohol secundario. Isopropanol."),
    _C(id="butan1ol", name_es="butan-1-ol", name_display="Butan-1-ol",
       name_iupac="Butan-1-ol", formula="C4H9OH", formula_display="C₄H₉OH",
       smiles="CCCCO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="intermedio",
       nomenclature_note="OH en C1. Alcohol primario."),
    _C(id="pentan1ol", name_es="pentan-1-ol", name_display="Pentan-1-ol",
       name_iupac="Pentan-1-ol", formula="C5H11OH", formula_display="C₅H₁₁OH",
       smiles="CCCCCO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="intermedio",
       nomenclature_note="OH en C1."),
    _C(id="hexan1ol", name_es="hexan-1-ol", name_display="Hexan-1-ol",
       name_iupac="Hexan-1-ol", formula="C6H13OH", formula_display="C₆H₁₃OH",
       smiles="CCCCCCO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="avanzado",
       nomenclature_note="OH en C1."),
    _C(id="etilenglicol", name_es="etilenglicol", name_display="Etilenglicol",
       name_iupac="Etano-1,2-diol", formula="C2H4(OH)2", formula_display="C₂H₄(OH)₂",
       smiles="OCCO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="avanzado",
       nomenclature_note="Diol. Anticongelante."),
    _C(id="glicerol", name_es="glicerol", name_display="Glicerol",
       name_iupac="Propano-1,2,3-triol", formula="C3H5(OH)3",
       formula_display="C₃H₅(OH)₃", smiles="OCC(O)CO", category="organica",
       subcategory="alcoholes", subcategory_display="Alcoholes",
       difficulty="avanzado",
       nomenclature_note="Triol. Glicerina."),

    # ---------- ÉTERES ----------
    _C(id="eter_dietilico", name_es="eter dietilico", name_display="Éter dietílico",
       name_iupac="Etoxietano", formula="C2H5OC2H5",
       formula_display="C₂H₅OC₂H₅", smiles="CCOCC", category="organica",
       subcategory="eteres", subcategory_display="Éteres",
       difficulty="intermedio",
       nomenclature_note="Dos cadenas etilo unidas por O. Disolvente."),
    _C(id="eter_dimetilico", name_es="eter dimetilico", name_display="Éter dimetílico",
       name_iupac="Metoximetano", formula="CH3OCH3", formula_display="CH₃OCH₃",
       smiles="COC", category="organica",
       subcategory="eteres", subcategory_display="Éteres",
       difficulty="basico",
       nomenclature_note="Éter más simple."),
    _C(id="eter_dibutilico", name_es="eter dibutilico", name_display="Éter dibutílico",
       name_iupac="Butoxibutano", formula="C4H9OC4H9",
       formula_display="C₄H₉OC₄H₉", smiles="CCCCOCCCC", category="organica",
       subcategory="eteres", subcategory_display="Éteres",
       difficulty="avanzado",
       nomenclature_note="Dos cadenas butilo unidas por O."),

    # ---------- ALDEHÍDOS ----------
    _C(id="metanal", name_es="metanal", name_display="Metanal",
       name_iupac="Metanal", formula="HCHO", formula_display="HCHO",
       smiles="C=O", category="organica",
       subcategory="aldehidos", subcategory_display="Aldehídos",
       difficulty="basico",
       nomenclature_note="Grupo -CHO terminal. Formaldehído."),
    _C(id="etanal", name_es="etanal", name_display="Etanal",
       name_iupac="Etanal", formula="CH3CHO", formula_display="CH₃CHO",
       smiles="CC=O", category="organica",
       subcategory="aldehidos", subcategory_display="Aldehídos",
       difficulty="basico",
       nomenclature_note="Acetaldehído. Sufijo -al."),
    _C(id="propanal", name_es="propanal", name_display="Propanal",
       name_iupac="Propanal", formula="C2H5CHO", formula_display="C₂H₅CHO",
       smiles="CCC=O", category="organica",
       subcategory="aldehidos", subcategory_display="Aldehídos",
       difficulty="intermedio",
       nomenclature_note="Aldehído de 3 C."),
    _C(id="butanal", name_es="butanal", name_display="Butanal",
       name_iupac="Butanal", formula="C3H7CHO", formula_display="C₃H₇CHO",
       smiles="CCCC=O", category="organica",
       subcategory="aldehidos", subcategory_display="Aldehídos",
       difficulty="intermedio",
       nomenclature_note="Aldehído de 4 C."),
    _C(id="pentanal", name_es="pentanal", name_display="Pentanal",
       name_iupac="Pentanal", formula="C4H9CHO", formula_display="C₄H₉CHO",
       smiles="CCCCC=O", category="organica",
       subcategory="aldehidos", subcategory_display="Aldehídos",
       difficulty="avanzado",
       nomenclature_note="Aldehído de 5 C."),
    _C(id="hexanal", name_es="hexanal", name_display="Hexanal",
       name_iupac="Hexanal", formula="C5H11CHO", formula_display="C₅H₁₁CHO",
       smiles="CCCCCC=O", category="organica",
       subcategory="aldehidos", subcategory_display="Aldehídos",
       difficulty="avanzado",
       nomenclature_note="Aldehído de 6 C."),

    # ---------- CETONAS ----------
    _C(id="propanona", name_es="propanona", name_display="Propanona",
       name_iupac="Propan-2-ona", formula="CH3COCH3", formula_display="CH₃COCH₃",
       smiles="CC(=O)C", category="organica",
       subcategory="cetonas", subcategory_display="Cetonas",
       difficulty="basico",
       nomenclature_note="C=O interno. Acetona. Sufijo -ona."),
    _C(id="butanona", name_es="butanona", name_display="Butanona",
       name_iupac="Butan-2-ona", formula="CH3COC2H5",
       formula_display="CH₃COC₂H₅", smiles="CC(=O)CC", category="organica",
       subcategory="cetonas", subcategory_display="Cetonas",
       difficulty="basico",
       nomenclature_note="Cetona de 4 C."),
    _C(id="pentan3ona", name_es="pentan-3-ona", name_display="Pentan-3-ona",
       name_iupac="Pentan-3-ona", formula="C2H5COC2H5",
       formula_display="C₂H₅COC₂H₅", smiles="CCC(=O)CC", category="organica",
       subcategory="cetonas", subcategory_display="Cetonas",
       difficulty="intermedio",
       nomenclature_note="C=O en C3."),
    _C(id="pentan2ona", name_es="pentan-2-ona", name_display="Pentan-2-ona",
       name_iupac="Pentan-2-ona", formula="CH3COC3H7",
       formula_display="CH₃COC₃H₇", smiles="CC(=O)CCC", category="organica",
       subcategory="cetonas", subcategory_display="Cetonas",
       difficulty="intermedio",
       nomenclature_note="C=O en C2. Isómero de pentan-3-ona."),
    _C(id="hexan2ona", name_es="hexan-2-ona", name_display="Hexan-2-ona",
       name_iupac="Hexan-2-ona", formula="CH3COC4H9",
       formula_display="CH₃COC₄H₉", smiles="CC(=O)CCCC", category="organica",
       subcategory="cetonas", subcategory_display="Cetonas",
       difficulty="avanzado",
       nomenclature_note="C=O en C2."),
    _C(id="heptan4ona", name_es="heptan-4-ona", name_display="Heptan-4-ona",
       name_iupac="Heptan-4-ona", formula="C3H7COC3H7",
       formula_display="C₃H₇COC₃H₇", smiles="CCCC(=O)CCC", category="organica",
       subcategory="cetonas", subcategory_display="Cetonas",
       difficulty="avanzado",
       nomenclature_note="C=O en C4 (centro)."),

    # ---------- ÁCIDOS CARBOXÍLICOS ----------
    _C(id="ac_metanoico", name_es="acido metanoico", name_display="Ácido metanoico",
       name_iupac="Ácido metanoico", formula="HCOOH", formula_display="HCOOH",
       smiles="C(=O)O", category="organica",
       subcategory="acidos_carboxilicos",
       subcategory_display="Ácidos carboxílicos",
       difficulty="basico",
       nomenclature_note="Grupo -COOH. Ácido fórmico (hormigas)."),
    _C(id="ac_etanoico", name_es="acido etanoico", name_display="Ácido etanoico",
       name_iupac="Ácido etanoico", formula="CH3COOH", formula_display="CH₃COOH",
       smiles="CC(=O)O", category="organica",
       subcategory="acidos_carboxilicos",
       subcategory_display="Ácidos carboxílicos",
       difficulty="basico",
       nomenclature_note="Ácido acético. Vinagre."),
    _C(id="ac_propanoico", name_es="acido propanoico", name_display="Ácido propanoico",
       name_iupac="Ácido propanoico", formula="C2H5COOH",
       formula_display="C₂H₅COOH", smiles="CCC(=O)O", category="organica",
       subcategory="acidos_carboxilicos",
       subcategory_display="Ácidos carboxílicos",
       difficulty="intermedio",
       nomenclature_note="Ácido de 3 C."),
    _C(id="ac_butanoico", name_es="acido butanoico", name_display="Ácido butanoico",
       name_iupac="Ácido butanoico", formula="C3H7COOH",
       formula_display="C₃H₇COOH", smiles="CCCC(=O)O", category="organica",
       subcategory="acidos_carboxilicos",
       subcategory_display="Ácidos carboxílicos",
       difficulty="intermedio",
       nomenclature_note="Ácido butírico (mantequilla rancia)."),
    _C(id="ac_pentanoico", name_es="acido pentanoico", name_display="Ácido pentanoico",
       name_iupac="Ácido pentanoico", formula="C4H9COOH",
       formula_display="C₄H₉COOH", smiles="CCCCC(=O)O", category="organica",
       subcategory="acidos_carboxilicos",
       subcategory_display="Ácidos carboxílicos",
       difficulty="avanzado",
       nomenclature_note="Ácido valérico."),
    _C(id="ac_hexanoico", name_es="acido hexanoico", name_display="Ácido hexanoico",
       name_iupac="Ácido hexanoico", formula="C5H11COOH",
       formula_display="C₅H₁₁COOH", smiles="CCCCCC(=O)O", category="organica",
       subcategory="acidos_carboxilicos",
       subcategory_display="Ácidos carboxílicos",
       difficulty="avanzado",
       nomenclature_note="Ácido caproico."),

    # ---------- ÉSTERES ----------
    _C(id="formiato_metilo", name_es="formiato de metilo",
       name_display="Formiato de metilo",
       name_iupac="Metanoato de metilo", formula="HCOOCH3",
       formula_display="HCOOCH₃", smiles="COC=O", category="organica",
       subcategory="esteres", subcategory_display="Ésteres",
       difficulty="intermedio",
       nomenclature_note="Éster del ácido metanoico con metanol."),
    _C(id="acetato_metilo", name_es="acetato de metilo",
       name_display="Acetato de metilo",
       name_iupac="Etanoato de metilo", formula="CH3COOCH3",
       formula_display="CH₃COOCH₃", smiles="COC(=O)C", category="organica",
       subcategory="esteres", subcategory_display="Ésteres",
       difficulty="intermedio",
       nomenclature_note="Éster del ácido etanoico con metanol."),
    _C(id="acetato_etilo", name_es="acetato de etilo",
       name_display="Acetato de etilo",
       name_iupac="Etanoato de etilo", formula="CH3COOC2H5",
       formula_display="CH₃COOC₂H₅", smiles="CCOC(=O)C", category="organica",
       subcategory="esteres", subcategory_display="Ésteres",
       difficulty="intermedio",
       nomenclature_note="Éster del ácido etanoico con etanol. Olor a frutas."),
    _C(id="propanoato_met", name_es="propanoato de metilo",
       name_display="Propanoato de metilo",
       name_iupac="Propanoato de metilo", formula="C2H5COOCH3",
       formula_display="C₂H₅COOCH₃", smiles="COC(=O)CC", category="organica",
       subcategory="esteres", subcategory_display="Ésteres",
       difficulty="avanzado",
       nomenclature_note="Éster del ácido propanoico con metanol."),
    _C(id="acetato_propilo", name_es="acetato de propilo",
       name_display="Acetato de propilo",
       name_iupac="Etanoato de propilo", formula="CH3COOC3H7",
       formula_display="CH₃COOC₃H₇", smiles="CCCOC(=O)C", category="organica",
       subcategory="esteres", subcategory_display="Ésteres",
       difficulty="avanzado",
       nomenclature_note="Éster del ácido etanoico con propanol."),

    # ---------- ANHÍDRIDOS ORGÁNICOS ----------
    _C(id="anhid_acetico", name_es="anhidrido acetico",
       name_display="Anhídrido acético",
       name_iupac="Anhídrido etanoico", formula="(CH3CO)2O",
       formula_display="(CH₃CO)₂O", smiles="CC(=O)OC(=O)C", category="organica",
       subcategory="anhidridos_organicos",
       subcategory_display="Anhídridos orgánicos",
       difficulty="avanzado",
       nomenclature_note="Dos ácidos acéticos unidos perdiendo H₂O."),
    _C(id="anhid_formico", name_es="anhidrido formico",
       name_display="Anhídrido fórmico",
       name_iupac="Anhídrido metanoico", formula="(HCO)2O",
       formula_display="(HCO)₂O", smiles="O=COC=O", category="organica",
       subcategory="anhidridos_organicos",
       subcategory_display="Anhídridos orgánicos",
       difficulty="avanzado",
       nomenclature_note="Dos ácidos fórmicos condensados."),

    # ---------- AMINAS ----------
    _C(id="metilamina", name_es="metilamina", name_display="Metilamina",
       name_iupac="Metanamina", formula="CH3NH2", formula_display="CH₃NH₂",
       smiles="CN", category="organica",
       subcategory="aminas", subcategory_display="Aminas",
       difficulty="basico",
       nomenclature_note="Grupo -NH₂. Amina primaria."),
    _C(id="etilamina", name_es="etilamina", name_display="Etilamina",
       name_iupac="Etanamina", formula="C2H5NH2", formula_display="C₂H₅NH₂",
       smiles="CCN", category="organica",
       subcategory="aminas", subcategory_display="Aminas",
       difficulty="basico",
       nomenclature_note="Amina primaria con cadena etilo."),
    _C(id="propilamina", name_es="propilamina", name_display="Propilamina",
       name_iupac="Propan-1-amina", formula="C3H7NH2", formula_display="C₃H₇NH₂",
       smiles="CCCN", category="organica",
       subcategory="aminas", subcategory_display="Aminas",
       difficulty="intermedio",
       nomenclature_note="Amina primaria de 3 C."),
    _C(id="butilamina", name_es="butilamina", name_display="Butilamina",
       name_iupac="Butan-1-amina", formula="C4H9NH2", formula_display="C₄H₉NH₂",
       smiles="CCCCN", category="organica",
       subcategory="aminas", subcategory_display="Aminas",
       difficulty="intermedio",
       nomenclature_note="Amina primaria de 4 C."),
    _C(id="anilina", name_es="anilina", name_display="Anilina",
       name_iupac="Fenilamina", formula="C6H5NH2", formula_display="C₆H₅NH₂",
       smiles="Nc1ccccc1", category="organica",
       subcategory="aminas", subcategory_display="Aminas",
       difficulty="avanzado",
       nomenclature_note="Amina aromática. Base de los colorantes azoicos."),

    # ---------- AMIDAS ----------
    _C(id="formamida", name_es="formamida", name_display="Formamida",
       name_iupac="Metanamida", formula="HCONH2", formula_display="HCONH₂",
       smiles="NC=O", category="organica",
       subcategory="amidas", subcategory_display="Amidas",
       difficulty="intermedio",
       nomenclature_note="Grupo -CONH₂. Amida más simple."),
    _C(id="acetamida", name_es="acetamida", name_display="Acetamida",
       name_iupac="Etanamida", formula="CH3CONH2", formula_display="CH₃CONH₂",
       smiles="CC(=O)N", category="organica",
       subcategory="amidas", subcategory_display="Amidas",
       difficulty="intermedio",
       nomenclature_note="Amida del ácido etanoico."),
    _C(id="propionamida", name_es="propionamida", name_display="Propanamida",
       name_iupac="Propanamida", formula="C2H5CONH2",
       formula_display="C₂H₅CONH₂", smiles="CCC(=O)N", category="organica",
       subcategory="amidas", subcategory_display="Amidas",
       difficulty="avanzado",
       nomenclature_note="Amida del ácido propanoico."),

    # ---------- NITRILOS ----------
    _C(id="acetonitrilo", name_es="acetonitrilo", name_display="Acetonitrilo",
       name_iupac="Etanonitrilo", formula="CH3CN", formula_display="CH₃CN",
       smiles="CC#N", category="organica",
       subcategory="nitrilos", subcategory_display="Nitrilos",
       difficulty="avanzado",
       nomenclature_note="Grupo -C≡N. Disolvente polar aprótico."),
    _C(id="propionitrilo", name_es="propionitrilo", name_display="Propanonitrilo",
       name_iupac="Propanonitrilo", formula="C2H5CN", formula_display="C₂H₅CN",
       smiles="CCC#N", category="organica",
       subcategory="nitrilos", subcategory_display="Nitrilos",
       difficulty="avanzado",
       nomenclature_note="Nitrilo de 3 C."),
    _C(id="benzonitrilo", name_es="benzonitrilo", name_display="Benzonitrilo",
       name_iupac="Bencenocarbonitrilo", formula="C6H5CN",
       formula_display="C₆H₅CN", smiles="N#Cc1ccccc1", category="organica",
       subcategory="nitrilos", subcategory_display="Nitrilos",
       difficulty="avanzado",
       nomenclature_note="Nitrilo aromático."),
]


# ---------------------------------------------------------------------------
# PUBLIC: COMPOUNDS (flat list)
# ---------------------------------------------------------------------------

COMPOUNDS: List[Dict] = _INORGANICA + _ORGANICA


# ---------------------------------------------------------------------------
# PUBLIC: TAXONOMY (nested for UI navigation)
# ---------------------------------------------------------------------------

def _build_taxonomy(compounds: List[Dict]) -> Dict:
    """Build the nested TAXONOMY structure from the flat compound list."""
    tax: Dict = {}
    for c in compounds:
        cat = c["category"]
        sub = c["subcategory"]
        if cat not in tax:
            # We'll set display name from the first compound of that category.
            display = "Química Inorgánica" if cat == "inorganica" else "Química Orgánica"
            tax[cat] = {"display": display, "subcategories": {}}
        if sub not in tax[cat]["subcategories"]:
            tax[cat]["subcategories"][sub] = {
                "display": c["subcategory_display"],
                "ids": [],
            }
        tax[cat]["subcategories"][sub]["ids"].append(c["id"])
    return tax


TAXONOMY: Dict = _build_taxonomy(COMPOUNDS)


# ---------------------------------------------------------------------------
# PUBLIC: get_compounds(...) filter
# ---------------------------------------------------------------------------

def get_compounds(category: Optional[str] = None,
                  subcategories: Optional[Iterable[str]] = None,
                  difficulty: Optional[Iterable[str]] = None) -> List[Dict]:
    """
    Filter the COMPOUNDS list.

    Args:
        category:     "inorganica" | "organica" | None (= both)
        subcategories: iterable of subcategory slugs (e.g. {"alcanos", "alquenos"})
                       None = all subcategories of the chosen category
        difficulty:   iterable of difficulty levels, or a single string
                       (e.g. "basico", or ["basico", "intermedio"])
                       None = all difficulties

    Returns:
        A new list of compound dicts (does not modify COMPOUNDS).
    """
    if isinstance(difficulty, str):
        difficulty = [difficulty]
    if isinstance(subcategories, str):
        subcategories = [subcategories]

    subset = COMPOUNDS
    if category is not None:
        subset = [c for c in subset if c["category"] == category]
    if subcategories is not None:
        wanted = set(subcategories)
        subset = [c for c in subset if c["subcategory"] in wanted]
    if difficulty is not None:
        wanted_d = set(difficulty)
        subset = [c for c in subset if c["difficulty"] in wanted_d]
    return subset


# ---------------------------------------------------------------------------
# Validation helpers (used by tests)
# ---------------------------------------------------------------------------

REQUIRED_KEYS = {
    "id", "name_es", "name_display", "name_iupac", "formula", "formula_display",
    "smiles", "category", "subcategory", "subcategory_display", "difficulty",
    "nomenclature_note", "ionic",
}


def validate_schema() -> List[str]:
    """Return a list of error strings (empty if every compound is well-formed)."""
    errors: List[str] = []
    seen_ids = set()
    for i, c in enumerate(COMPOUNDS):
        missing = REQUIRED_KEYS - set(c.keys())
        if missing:
            errors.append(f"[#{i} id={c.get('id','?')}] missing keys: {missing}")
        if c["id"] in seen_ids:
            errors.append(f"[#{i}] duplicate id: {c['id']!r}")
        seen_ids.add(c["id"])
        if c["category"] not in {"inorganica", "organica"}:
            errors.append(f"[#{i} id={c['id']}] bad category: {c['category']!r}")
        if c["difficulty"] not in {"basico", "intermedio", "avanzado"}:
            errors.append(f"[#{i} id={c['id']}] bad difficulty: {c['difficulty']!r}")
    return errors


if __name__ == "__main__":
    errors = validate_schema()
    if errors:
        print(f"VALIDATION FAILED — {len(errors)} error(s):")
        for e in errors:
            print("  -", e)
    else:
        print(f"OK — {len(COMPOUNDS)} compounds, schema valid.")
        print(f"     inorganica: {sum(1 for c in COMPOUNDS if c['category']=='inorganica')}")
        print(f"     organica:   {sum(1 for c in COMPOUNDS if c['category']=='organica')}")
        print(f"     subcategorias: {sum(len(v['subcategories']) for v in TAXONOMY.values())}")
